### ISSUE TITLE
Eval and inspect.getsource(func) are not compatible 

### ISSUE THREAD

**Issue by markNZed** [gilad-rubin/hypster#6]
I am far from a Python expert but it seems to me if the code uses eval to create a function then it cannot later get the source for that function using inspect.getsource(func) This is an issue when trying to hp.propagate and the config function being propagated also includes hp.propagate One way of working around this is to import the config and pass the config function to the hp.propagate instead of using hypster.load

**Comment by gilad-rubin** [comment]
Thanks for raising this issue.
It is possible to have multiple nested configurations using hp.propagate.

Can you please provide a code example so that I can try and help more specifically?

**Comment by markNZed** [comment]
I can't provide an example, sorry. I think the issue is a general property of Python - if we use eval then try to get source information using  inspect.getsource(func) it will not be able to return a source location. Do you have a test showing recursive propagate with configurations in separate files?

**Comment by gilad-rubin** [comment]
Yes, here:
https://github.com/gilad-rubin/hypster/blob/779e502fe1bdc0231a03a7769a7403d6bbe9e024/tests/test_hp_calls/test_propagation.py#L133

**Comment by markNZed** [comment]
middle_config.py is in the repo ? I could not find it sorry.

**Comment by gilad-rubin** [comment]
it's here:

https://github.com/gilad-rubin/hypster/blob/779e502fe1bdc0231a03a7769a7403d6bbe9e024/tests/test_hp_calls/test_propagation.py#L20

when you run the test - it saves the module to the tests/helper_configs folder

**Comment by markNZed** [comment]
I wonder if defining those configs inside the test may hide issues. If you have those files on disk and you do not create/define the config inside the test module then it might show problems. I would try to have the files as standalone to get closer to what the user will do.

**Comment by gilad-rubin** [comment]
This will work as standalone. When we reach the test that uses middle config - it just reads from the directory. 
The reason that I don't have them as standalone files has to do with some annoying issues I had with version control.

Thanks for the comments so far. 

Please let me know if you have any difficulties working with propagate or any other feature. Pasting in a code example would help me to guide you more concretely.

**Comment by gilad-rubin** [comment]
Please also note that I just changed hp.propagate to hp.nest throughout the project. I believe it's a clearer name.
Hopefully this will be last breaking change in the main syntax of the framework.

**Comment by markNZed** [comment]
If I search the code base on GitHub I can't find where you use eval in the code. So I guess you removed it ? If you did then you can close this issue.
