### ISSUE TITLE
0.2.25 Broken

### ISSUE THREAD

**Issue by markNZed** [gilad-rubin/hypster#7]
$ pip install hypster==0.2.24
Defaulting to user installation because normal site-packages is not writeable
Collecting hypster==0.2.24
  Downloading hypster-0.2.24-py3-none-any.whl.metadata (2.7 kB)
Downloading hypster-0.2.24-py3-none-any.whl (23 kB)
Installing collected packages: hypster
  Attempting uninstall: hypster
    Found existing installation: hypster 0.2.23
    Uninstalling hypster-0.2.23:
      Successfully uninstalled hypster-0.2.23
Successfully installed hypster-0.2.24
$ python3 hypster_test2.py 
{'model': 'model_b'}
$ pip install hypster==0.2.25
Defaulting to user installation because normal site-packages is not writeable
Collecting hypster==0.2.25
  Downloading hypster-0.2.25-py3-none-any.whl.metadata (2.7 kB)
Downloading hypster-0.2.25-py3-none-any.whl (35 kB)
Installing collected packages: hypster
  Attempting uninstall: hypster
    Found existing installation: hypster 0.2.24
    Uninstalling hypster-0.2.24:
      Successfully uninstalled hypster-0.2.24
Successfully installed hypster-0.2.25
$ python3 hypster_test2.py 
Traceback (most recent call last):
  File "hypster_test2.py", line 8, in <module>
    results = simple_config(selections={"model": "model_b"})
TypeError: Hypster.__call__() got an unexpected keyword argument 'selections'
$ cat hypster_test2.py 
from hypster import HP, config

@config
def simple_config(hp: HP):
    # Define a basic selection with a default
    model = hp.select(["model_a", "model_b"], default="model_a")

results = simple_config(selections={"model": "model_b"})
print(results)

**Comment by gilad-rubin** [comment]
Thanks for raising this issue. Hypster has been through a lot of changes in the past two weeks and some of the core API has changed.

There is now support for "values" instead of "selections" and "overrides". This is meant to simplify the use of the package.

Please refer to the updated documentation:
https://gilad-rubin.gitbook.io/hypster/

**Comment by markNZed** [comment]
For the future I highly recommend refactoring on a branch. I had to stop using Hypster because it was unstable :(
